### ISSUE TITLE
Fraction: add 'isGreaterThan'

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phetcommon#42]
@jonathanolson added `isLessThan` in https://github.com/phetsims/phetcommon/commit/64e7c872674dd861b8cf8f59a475a02958a8b945.  Why wasn't `isGreaterThan` added at the same time?  It would have been way less expensive to add it (and its unit tests) at the same time.  If you needed `isLessThan`, then surely someone is going to need `isGreaterThan` sometime.  

Sorry to pick on @jonathanolson here, because he's by no means the only offender. But `Fractions` in particular has been an example of "I'm going to add only what I need, and let someone else worry about what they need."   Confirmed by this comment that still exists at the top of Fraction:

```js
 * NOTE: The common version of this class in the PhET Java code base has a number of additional methods.  These methods
 * should be ported into this file as needed.  Please see edu.colorado.phet.fractions.common.math.Fraction.java in the
 * PhET Java code base.
```

Since I spent almost an entire day adding very _basic_ functionality to Fraction in https://github.com/phetsims/phetcommon/issues/41 (for Equality Explorer), it peeves me  to see more of this "only what I need" approach to enhancing common code.

**Comment by jonathanolson** [comment]
> Why wasn't isGreaterThan added at the same time?

I was thinking of it mathematically, where that one function is the main building block. I typically orient comparisons as less-thans, and felt no need to have a greater-than personally. We've run into many cases where people have preferred simpler core types to having more helper methods (e.g. `Property.onValue`, `Property.once`, DerivedProperty convenience functions, so I've lately tried to avoid the "toss the kitchen sink of methods in". Otherwise I could imagine:

- isGreaterThan
- isGreaterThanOrEqual
- isLessThanOrEqual
- isPositive
- isNegative
- etc., and that's almost a page of code for wrappers based on the one function. (I probably would add at least `isLessThanOrEqual` and some fraction constants like 0 and 1)

I'm happy to err more on the side of adding things (if you've seen Node or Vector2, I used to add many more helper functions), just let me know.

> It would have been way less expensive to add it (and its unit tests) at the same time.

True, but writing tests for many different variations of the same function felt like it would take a lot of time, so I focused more on sim priorities.

> If you needed isLessThan, then surely someone is going to need isGreaterThan sometime.

Personally I didn't feel the need, as `a.isGreaterThan( b ) === b.isLessThan( a )`, similarly to how we don't have `childNode.addParent( parentNode )`.

If we're discussing at the developer meeting, I guess:

1. What should we do for this case (Fraction)?
2. Generally, do people prefer more helper functions?
3. And if we want more helper functions, can we add back in `Property.once`? Yesterday I ran across a perfect use case for it. I've also in the last few days run across things where `Property.onValue` and the DerivedProperty `sum` and `all/every` equivalent functions would have been used, so I have no shortage of desires for that type of method/function.

**Comment by pixelzoom** [comment]
I'm going to close this.  Guess I'm still just upset about the amount of work I had to do to add basic stuff to Fraction that should have been ported in the first place.  And grousing about it is unlikely to change behavior, more likely to get people upset with me. 

Personally, I don't want to see a proliferation of convenience methods.  If you feel otherwise, open a new issue to discuss. 

Closing.
