### ISSUE TITLE
Add Fraction.fromDecimal

### ISSUE THREAD

**Issue by zepumph** [phetsims/phetcommon#53]
My thought is a function that given a decimal, it returns a Fraction. This will greatly help me over in https://github.com/phetsims/ratio-and-proportion/issues/249.

**Comment by zepumph** [comment]
@pixelzoom will you please review this addition since you have many commits in Fraction.js. Also take a look at the unit tests, and limitations about irrational numbers (though not surprising. What do you think about this convenience function.

Also, would you want to use it in https://github.com/phetsims/graphing-lines/blob/585fa2983366a813d465d9ae257c5afaaea51156/js/common/model/Line.js#L161-L170? Probably not, but I thought I'd ask.

**Comment by pixelzoom** [comment]
While experimenting with `fromDecimal` to understand how it works, I discovered that Fractions.js is missing `phetcommon.register`.  Added in the above commit.

**Comment by pixelzoom** [comment]
`fromDecimal` seems to work, but....

* Needs more comments.  It's not obvious how it works, due to the next points.
* There are multiple `return` statements.  They're tolerable in simple/obvious algorithms.  But otherwise they make algorithms more difficult to understand/maintain, especially when the `else` clause of an `if` statement is omitted, as in this case.
* The case when `number` is an integer can be handled sooner, before splitting the number into whole and decimal.
* `decimal` starts as the decimal portion of the value (line 378), then morphs into something else on line 390. Recommend not to recycle variables in this way. 
* `expandingNumber` is a string from lines 384-389, then it suddenly becomes a number on line 390.  Again, recommended not to not recycle variables in this way, and separate into `expandingString` and `expandingNumber` (or better yet `numerator`, because that's what it is) and make the type conversion explicit.
* Doesn't leverage dot.Utils for things like `numberOfDecimalPlaces`.

... and overall it just seems unnecessarily complicated.

Here's a much simpler implementation (not committed) that passes unit tests:

```js
  /**
   * Convert a number into a Fraction
   * @public
   * @param {number} number - integer or float, doesn't matter
   * @returns {Fraction}
   */
  static fromDecimal( number ) {

    if ( Utils.isInteger( number ) ) {
      return Fraction.fromInteger( number );
    }
    else {

      // Get the decimal part of the number.
      const decimal = number - Utils.toFixedNumber( number, 0 );
      assert && assert( decimal !== 0, 'expected decimal to be non-zero' );

      // Convert the decimal part into an integer. This becomes the denominator.
      const denominator = Math.pow( 10, Utils.numberOfDecimalPlaces( decimal ) );

      // Compute numerator
      const numerator = Utils.toFixedNumber( number * denominator, 0 );

      return new Fraction( numerator, denominator ).reduce();
    }
  }
```

**Comment by zepumph** [comment]
Yes, that is tremendously better. Thank you so much. I reviewed and committed. I found that it worked well in my use case in RaP too. Closing
