### ISSUE TITLE
Add PatternStringProperty

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/phetcommon#58]
Also, PSA for its existence at developer meeting, and to decide on a code review

**Comment by pixelzoom** [comment]
Review:

* In the above commits, I used PatternStringProperty in molecule-polarity. It's working nicely, and `grunt generate-phet-io-api` did not result in any API changes.
* The API is very nice.
* The implementation is complicated, some ninja TypeScript here. I'd hate to have to debug it.
* PatternStringProperty lives in phetcommon/js/util/, which makes it dependent on axon. Is that OK?
* II would move PatternStringProperty to axon because (1) that's where StringProperty, StringEnumerationProperty, etc. live, (2) no other Properties live in phetcommon, (3) WebStorm imports are broken, and it will be more convenient to copy another axon import, and (4) there is a long-standing issue to make phetcommon go away https://github.com/phetsims/phetcommon/issues/24.

Back to @jonathanolson.

**Comment by pixelzoom** [comment]
One more thing... If deriving a string requires any logic, then PatternStringProperty is not a good fit. 

For example, in OpticalObjectLabelNode.ts:

```typescript
const labelStringProperty = new DerivedProperty( [
      options.isNumberedProperty,
      geometricOpticsStrings.label.objectStringProperty,
      geometricOpticsStrings.label.objectNStringProperty
    ], (
      isNumbered: boolean,
      objectString: string,
      objectNString: string
    ) => isNumbered ? StringUtils.fillIn( objectNString, { objectNumber: objectNumber } ) : objectString, {
      tandem: options.tandem.createTandem( 'labelStringProperty' ),
      phetioValueType: StringIO
    } );
```

This is an example of what `StringUtils.fillIn` should not be deprecated.

**Comment by pixelzoom** [comment]
In the above commit, I also used PatternStringProperty in natural-selection.  It's now used wherever appropriate my sims that support dynamic locale.

**Comment by jonathanolson** [comment]
@samreid do you know the status of TypeScript and inter-repo circular dependencies?

Usually, dot relies on axon (Vector2Property, emitters in Transform3, etc.). However NumberProperty relies on Range (axon relying on dot).

Since Utils.toFixed and Range are never going to rely on axon things, we SHOULD be file-level-safe with intermingled dependencies if axon uses those.

So... will it be bad if I move over phetcommon things to axon that have dot dependencies in them?

**Comment by jonathanolson** [comment]
> The implementation is complicated, some ninja TypeScript here. I'd hate to have to debug it.

Agreed. To me, it seemed beneficial to be able to give clients additional type safety in exchange for some more complicated common code.

> One more thing... If deriving a string requires any logic, then PatternStringProperty is not a good fit.

Yes, that's a good example, and not planning on deprecating fillIn.

**Comment by samreid** [comment]
> @samreid do you know the status of TypeScript and inter-repo circular dependencies?

I believe these are fine as long as they are in type space and not value space. (Did not work with project references but does work with our new monolithic tsconfig).

> So... will it be bad if I move over phetcommon things to axon that have dot dependencies in them?

What do you want to move in particular?  Does my prior answer also help answer this question too?

**Comment by jonathanolson** [comment]
Moved it to axon above. @pixelzoom anything else to do here?

**Comment by pixelzoom** [comment]
👍🏻 closing

**Comment by pixelzoom** [comment]
There was a typo in axon's main.js that was causing a CT error. Fixed in the above commit.

**Comment by jonathanolson** [comment]
Apologies!
